use Tests

--1
Select ENAME,JOB FROM EMPLOYEES WHERE JOB = 'MANAGER'

--2
SELECT ENAME , SAL FROM EMPLOYEES WHERE SAL > 1000

--3
SELECT ENAME,SAL FROM EMPLOYEES WHERE ENAME != 'JAMES'

--4
SELECT * FROM EMPLOYEES WHERE ENAME LIKE 'S%'

--5
SELECT * FROM EMPLOYEES WHERE ENAME LIKE '%A%'

--6
SELECT * FROM EMPLOYEES WHERE ENAME LIKE '__L%'

--7 
SELECT ENAME, SAL/30 as DAILY_SALARY FROM EMPLOYEES WHERE ENAME= 'JONES '

--8
SELECT SUM(SAL) AS TOTAL_MONTHLY_SALARY FROM EMPLOYEES  

--9
SELECT AVG(SAL*12) AS Average_annual_salary FROM EMPLOYEES

--10
SELECT ENAME,JOB,SAL,DEPTNO FROM EMPLOYEES  WHERE JOB != 'SALESMAN' AND DEPTNO = 30

--11
SELECT DISTINCT(DNAME) FROM DEPT

--12
SELECT ENAME AS EMPLOYEES,SAL AS MONTHLY_SALARY FROM EMPLOYEES WHERE SAL>1500 AND DEPTNO IN (10,30) 

--13
SELECT ENAME ,JOB,SAL FROM EMPLOYEES WHERE JOB IN ('MANAGER' , 'ANALYST') AND SAL NOT IN (1000,3000,5000)

--14
SELECT ENAME,SAL ,COMM FROM EMPLOYEES WHERE COMM>SAL*1.1

--15
SELECT ENAME FROM EMPLOYEES WHERE ENAME LIKE '%L%L' AND (DEPTNO = 30 OR MGR_ID = 7782)

--16
SELECT ENAME FROM EMPLOYEES WHERE DATEDIFF(YEAR, HIREDATE, GETDATE()) BETWEEN 30 AND 40

--17
SELECT ENAME,JOB FROM EMPLOYEES ORDER BY JOB ASC,ENAME DESC

--18
SELECT ENAME,DATEDIFF(YEAR, HIREDATE, GETDATE()) AS EXPERIENCE FROM EMPLOYEES WHERE ENAME ='MILLER'